branch-defaults:
  default:
    environment: budgeting-env
  dev-test:
    environment: budgeting-env
  main:
    environment: null
environment-defaults:
  test-dev:
    branch: null
    repository: null
global:
  application_name: budgeting
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: af-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
